### ISSUE TITLE
Add timeout verification to handle "no internet"

### ISSUE THREAD

**Issue by abbf** [rafoli/lessteps#4]
Please add an internet check to bypass the version update in order to continue with the flow that does not depend on the internet connection.

i.e.: "les -d"  -> Continue with the install and deploy tasks even when thaere is no internet connection.

**Comment by rafoli** [comment]
Fixed by https://github.com/rafoli/lessteps/commit/a4fb088274d24dd6892675f3acad3b78ba505361
